# Generated by Django 5.0.4 on 2024-05-01 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieorder',
            old_name='order',
            new_name='user',
        ),
    ]
